# Generated by Django 4.0.4 on 2024-10-11 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='user_images/default.png', upload_to='user_images', verbose_name='Фото сотрудника')),
                ('userlastname', models.CharField(default=None, max_length=50, null=True, verbose_name='Фамилия')),
                ('userfirstname', models.CharField(default=None, max_length=50, null=True, verbose_name='Имя')),
                ('userpatronymic', models.CharField(default=None, max_length=50, null=True, verbose_name='Отчество')),
                ('userposition', models.CharField(default=None, max_length=50, null=True, verbose_name='Должность')),
                ('usertelnumber', models.CharField(default=None, max_length=50, null=True, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
    ]
