# Generated by Django 4.0.4 on 2024-10-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userfirstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userlastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userpatronymic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usertelnumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='ФИО/роль'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Идентификатор организации=ИНН_ГГММДД регистрации)'),
        ),
    ]
