# Generated by Django 4.0.4 on 2024-10-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_remove_profile_userfirstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pay',
            field=models.BooleanField(default=True, verbose_name='Оплачено'),
        ),
    ]
