# Generated by Django 4.0.4 on 2024-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userposition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
