# Generated by Django 4.0.4 on 2024-10-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_userposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Идентификатор организации (10 случайных цифр)')),
                ('name', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Название организации')),
                ('requisits', models.TextField(blank=True, default=None, max_length=40, null=True, verbose_name='Реквизиты организации')),
                ('adress', models.TextField(blank=True, default=None, max_length=40, null=True, verbose_name='Адрес организации юридический')),
                ('adress_lab', models.TextField(blank=True, default=None, max_length=40, null=True, verbose_name='Адрес лаборатории физический')),
                ('phone', models.TextField(blank=True, default=None, max_length=15, null=True, verbose_name='Телефон организации юридический')),
                ('phone_lab', models.TextField(blank=True, default=None, max_length=15, null=True, verbose_name='Телефон лаборатории')),
                ('direktor_position', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Должность главного лица компании')),
                ('direktor_name', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='ФИО главного лица компании')),
                ('headlab_position', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Должность главного лица лаборатории')),
                ('headlab_name', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='ФИО главного лица лаборатории')),
                ('email', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='email организации')),
                ('pay', models.BooleanField(default=True, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Идентификатор организации (10 случайных цифр)'),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Должность')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.company', verbose_name='Идентификатор организации')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
