# Generated by Django 4.0.4 on 2024-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_alter_profile_userid_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес организации юридический'),
        ),
        migrations.AlterField(
            model_name='company',
            name='adress_lab',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес лаборатории физический'),
        ),
        migrations.AlterField(
            model_name='company',
            name='direktor_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ФИО главного лица компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='headlab_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ФИО главного лица лаборатории'),
        ),
        migrations.AlterField(
            model_name='company',
            name='headlab_position',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Должность главного лица лаборатории'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='requisits',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Реквизиты организации'),
        ),
    ]
