# Generated by Django 4.0.4 on 2024-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_company_adress_alter_company_adress_lab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attestat',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Аттестат аккредитации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Телефон организации юридический'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_lab',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Телефон лаборатории'),
        ),
        migrations.AlterField(
            model_name='company',
            name='userid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Идентификатор организации (10 случайных цифр)'),
        ),
    ]
