# Generated by Django 4.0.4 on 2024-10-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_company_attestat_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='caretaker_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ФИО завхоза'),
        ),
        migrations.AddField(
            model_name='company',
            name='caretaker_position',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Должность завхоза'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ФИО лица ответственного за оборудование'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager_position',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Должность лица ответственного за оборудование'),
        ),
    ]
