# Generated by Django 4.0.4 on 2024-11-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_company_caretaker_name_company_caretaker_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='manager_email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='email лица ответственного за оборудование'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager_phone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='телефон лица ответственного за оборудование'),
        ),
    ]
