# Generated by Django 4.0.4 on 2024-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_company_manager_email_company_manager_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_big',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Название организации полное'),
        ),
        migrations.AddField(
            model_name='company',
            name='ver_agreement_card',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер учетной карточки у с организации-поверителя'),
        ),
        migrations.AddField(
            model_name='company',
            name='ver_agreement_date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Дата договора с организацией-поверителем'),
        ),
        migrations.AddField(
            model_name='company',
            name='ver_agreement_head_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кому: имя лица организации-поверителя'),
        ),
        migrations.AddField(
            model_name='company',
            name='ver_agreement_head_organisation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кому: название организации-поверителя'),
        ),
        migrations.AddField(
            model_name='company',
            name='ver_agreement_head_position',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кому: должность лица организации-поверителя'),
        ),
        migrations.AddField(
            model_name='company',
            name='ver_agreement_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер договора с организацией-поверителем'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Название организации краткое'),
        ),
    ]
