# Generated by Django 4.0.4 on 2024-11-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_company_name_big_company_ver_agreement_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='orderform',
            field=models.CharField(choices=[('ФБУ «Тест-С.-Петербург»', 'ФБУ «Тест-С.-Петербург»')], max_length=300, null=True, verbose_name='Форма заявки на поверку'),
        ),
    ]
