# Generated by Django 4.0.4 on 2024-11-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_orderform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='orderform',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ver_agreement_card',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ver_agreement_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ver_agreement_head_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ver_agreement_head_organisation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ver_agreement_head_position',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ver_agreement_number',
        ),
    ]
