# Generated by Django 4.0.4 on 2024-11-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_company_orderform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Телефон организации юридический'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_lab',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Телефон лаборатории'),
        ),
        migrations.AlterField(
            model_name='company',
            name='userid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Идентификатор организации (20 случайных цифр и латинских букв)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Идентификатор организации (20 случайных цифр и латинских букв)'),
        ),
    ]
