# Generated by Django 4.0.4 on 2025-02-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_company_phone_alter_company_phone_lab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pay',
        ),
        migrations.AddField(
            model_name='profile',
            name='rights',
            field=models.CharField(choices=[('Сотрудник', 'Сотрудник'), ('Менеджер', 'Менеджер')], default='Cотрудник', max_length=40, null=True, verbose_name='Права учетной записи'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='ФИО'),
        ),
    ]
