# Generated by Django 4.0.4 on 2025-02-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_pay_profile_rights_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rights',
        ),
    ]
