# Generated by Django 4.0.4 on 2025-02-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_phone',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='телефон'),
        ),
    ]
