# Generated by Django 4.0.4 on 2025-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_user_email_profile_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, default=1, max_length=50, null=True, verbose_name='Идентификатор организации (20 случайных цифр и латинских букв)'),
        ),
    ]
