# Generated by Django 4.0.4 on 2025-02-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_name_alter_profile_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='attestat',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Аттестат аккредитации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Название организации краткое'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_big',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Название организации полное'),
        ),
    ]
