# Generated by Django 4.0.4 on 2025-02-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_company_attestat_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ФИО кратко для документов'),
        ),
    ]
