# Generated by Django 4.2.19 on 2025-04-03 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0019_profile_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="ballance",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=18, verbose_name="Балланс счёта"
            ),
        ),
        migrations.CreateModel(
            name="CompanyBalanceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "reason",
                    models.IntegerField(
                        choices=[
                            (
                                "Пополнение счёта автоматическое",
                                "Пополнение счёта автоматическое",
                            ),
                            (
                                "Пополнение счёта оператором",
                                "Пополнение счёта оператором",
                            ),
                            (
                                "Автоматическое списание ежемесячного платежа",
                                "Автоматическое списание ежемесячного платежа",
                            ),
                            ("Другое", "Другое"),
                        ],
                        verbose_name="Пополнение счёта автоматическое",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6, default=0, max_digits=18, verbose_name="Сумма"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatorbalancechange",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updatorbalancechange",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
