# Generated by Django 4.2.19 on 2025-04-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_company_created_at_company_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companybalancechange",
            options={
                "verbose_name": "Изменения балланса компании",
                "verbose_name_plural": "Изменения балланса компании",
            },
        ),
    ]
