# Generated by Django 4.2.19 on 2025-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_companybalancechange_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companybalancechange",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Пополнение счёта автоматическое",
                        "Пополнение счёта автоматическое",
                    ),
                    ("Пополнение счёта оператором", "Пополнение счёта оператором"),
                    (
                        "Автоматическое списание ежемесячного платежа",
                        "Автоматическое списание ежемесячного платежа",
                    ),
                    ("Другое", "Другое"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Источник изменения",
            ),
        ),
    ]
