# Generated by Django 4.2.19 on 2025-04-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_alter_companybalancechange_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="ballance",
            new_name="balance",
        ),
    ]
