# Generated by Django 4.2.19 on 2025-04-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_rename_ballance_company_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="payement_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Дата платежа"
            ),
        ),
    ]
