# Generated by Django 4.2.19 on 2025-04-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_company_payement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="payement_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Дата платежа"
            ),
        ),
    ]
