# Generated by Django 4.2.19 on 2025-04-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_company_payement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybalancechange",
            name="document",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Номер документа",
            ),
        ),
    ]
