# Generated by Django 4.2.19 on 2025-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_companybalancechange_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companybalancechange",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, verbose_name="Сумма"
            ),
        ),
    ]
