# Generated by Django 4.2.19 on 2025-04-08 04:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_companybalancechange_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3000"),
                max_digits=18,
                verbose_name="Балланс счёта",
            ),
        ),
    ]
