# Generated by Django 4.2.19 on 2025-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_company_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="main_user",
            field=models.BooleanField(
                default=False, verbose_name="Главный пользователь - галочка если да"
            ),
        ),
    ]
