# Generated by Django 4.2.19 on 2025-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_companyactiveemployeslists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, verbose_name="Балланс счёта"
            ),
        ),
    ]
