# Generated by Django 4.2.19 on 2026-02-14 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0032_alter_company_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="user_images/default.png",
                        upload_to="user_images",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя изучение химии",
                "verbose_name_plural": "Профили пользователей изучение химии",
            },
        ),
    ]
