# Generated by Django 4.2.19 on 2026-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_chemprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="short_name",
            field=models.CharField(
                blank=True,
                default=1,
                max_length=40,
                null=True,
                verbose_name="ФИО кратко для документов",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_email",
            field=models.CharField(
                blank=True, default=1, max_length=40, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_phone",
            field=models.CharField(
                blank=True, default=1, max_length=40, null=True, verbose_name="телефон"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="userid",
            field=models.CharField(
                blank=True,
                default="chem",
                max_length=50,
                null=True,
                verbose_name="Идентификатор организации (20 случайных цифр и латинских букв)",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="userposition",
            field=models.CharField(
                blank=True,
                default=1,
                max_length=50,
                null=True,
                verbose_name="Должность",
            ),
        ),
        migrations.DeleteModel(
            name="ChemProfile",
        ),
    ]
