# Generated by Django 5.2.16 on 2026-08-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('путешествия', 'путешествия'), ('книги', 'книги'), ('фильмы', 'фильмы'), ('музеи', 'музеи'), ('учебные курсы', 'учебные курсы'), ('рецепты', 'рецепты'), ('покупки', 'покупки'), ('фотоальбом', 'фотоальбом'), ('прогулка', 'прогулка'), ('поездка на выходные', 'поездка на выходные'), ('аудио', 'аудио'), ('работа', 'работа')], default='путешествия', max_length=10000, null=True, verbose_name='Раздел')),
                ('undertype', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Подраздел')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('country', models.CharField(blank=True, default='Россия', max_length=10000, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default='Любой', max_length=10000, null=True, verbose_name='Регион (город)')),
                ('vk', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка на источник')),
                ('done', models.BooleanField(default=False, null=True, verbose_name='Использовано ли?')),
            ],
            options={
                'verbose_name': 'Закладки по темам',
                'verbose_name_plural': 'Закладки по темам',
            },
        ),
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='любой', max_length=10000, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('vk', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка')),
                ('photo', models.ImageField(blank=True, default='user_images/default1.png', null=True, upload_to='user_images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Химия',
                'verbose_name_plural': 'Химия',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='любой', max_length=10000, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('vk', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка')),
                ('photo', models.ImageField(blank=True, default='user_images/default1.png', null=True, upload_to='user_images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Закладки семья',
                'verbose_name_plural': 'Закладки семья',
            },
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_long', models.IntegerField(blank=True, default='1', null=True, verbose_name='Сколько дней')),
                ('season', models.CharField(blank=True, choices=[('теплое время года', 'теплое время года'), ('лето', 'лето'), ('зима', 'зима'), ('весна', 'весна'), ('осень', 'осень')], default='теплое время года', max_length=10000, null=True, verbose_name='Сезон')),
                ('country', models.CharField(blank=True, default='Россия', max_length=10000, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default='Северо-Запад', max_length=10000, null=True, verbose_name='Регион')),
                ('title', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Заголовок')),
                ('reality', models.BooleanField(blank=True, default=False, null=True, verbose_name='Пройдено')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата добавления записи')),
                ('start_station', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Вокзал отправления туда')),
                ('aim_station', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Вокзал прибытия туда')),
                ('home_station', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Вокзал прибытия оттуда')),
                ('back_station', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Вокзал отправления оттуда')),
                ('travel_details', models.TextField(blank=True, null=True, verbose_name='Подробности добирания и комментарии')),
                ('attractions', models.TextField(blank=True, null=True, verbose_name='Достопримечательности')),
                ('kilometers', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Примерный километраж')),
                ('vk', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка на встречу вк')),
                ('track', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка на трек')),
                ('img_track_project', models.ImageField(blank=True, default='user_images/default1.png', null=True, upload_to='user_images', verbose_name='Трек план')),
                ('img_track_fact', models.ImageField(blank=True, default='user_images/default1.png', null=True, upload_to='user_images', verbose_name='Трек факт')),
                ('dates_try', models.CharField(blank=True, default='в планах', max_length=10000, null=True, verbose_name='Даты прохождения')),
                ('maturity', models.BooleanField(blank=True, default=False, null=True, verbose_name='Готов ли маршрут?')),
            ],
            options={
                'verbose_name': 'Хайкинг',
                'verbose_name_plural': 'Хайкинг',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century', models.IntegerField(blank=True, default='1', null=True, verbose_name='Век')),
                ('year', models.IntegerField(blank=True, default='800', null=True, verbose_name='Год начала')),
                ('region', models.CharField(blank=True, choices=[('Северо-Западный регион', 'Северо-Западный регион'), ('Россия', 'Россия'), ('Европа', 'Европа'), ('Азия', 'Азия'), ('США', 'США')], default='Россия', max_length=10000, null=True, verbose_name='Регион')),
                ('type', models.CharField(blank=True, choices=[('История', 'История'), ('Культура', 'Культура')], default='История', max_length=10000, null=True, verbose_name='Тип')),
                ('cat', models.CharField(blank=True, choices=[('-', '-'), ('Воцарение правителя', 'Воцарение правителя'), ('Война', 'Война'), ('Территориальные изменения', 'Территориальные изменения')], default='-', max_length=10000, null=True, verbose_name='Категория')),
                ('title', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_long', models.TextField(blank=True, null=True, verbose_name='Подробности и ссылки')),
                ('photo1', models.ImageField(blank=True, default='user_images/default1.png', null=True, upload_to='user_images', verbose_name='Иллюстрация1')),
                ('photo2', models.ImageField(blank=True, default='user_images/default1.png', null=True, upload_to='user_images', verbose_name='Иллюстрация2')),
                ('photo3', models.ImageField(blank=True, default='user_images/default1.png', null=True, upload_to='user_images', verbose_name='Иллюстрация3')),
                ('photo4', models.ImageField(blank=True, default='user_images/default1.png', null=True, upload_to='user_images', verbose_name='Иллюстрация4')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Историческая картина мира',
            },
        ),
        migrations.CreateModel(
            name='Itbookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='любой', max_length=10000, null=True, verbose_name='Раздел')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('vk', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Записная книжка по айти',
                'verbose_name_plural': 'Записная книжка по айти',
            },
        ),
        migrations.CreateModel(
            name='Kareliahistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Раздел')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('vk', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'История Карелии',
                'verbose_name_plural': 'История Карелии',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('text', models.TextField(default='', max_length=1000, verbose_name='Содержание')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('forNote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='hike.hike', verbose_name='К записи')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-pk'],
            },
        ),
    ]
