# Generated by Django 4.0.4 on 2024-10-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_roomschange_personchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkequipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проверки')),
                ('datedead', models.DateField(blank=True, null=True, verbose_name='Дата окончания срока проверки')),
                ('dateorder', models.DateField(blank=True, null=True, verbose_name='Дата следующей проверки план')),
                ('certnumber', models.CharField(blank=True, max_length=90, null=True, verbose_name='Номер протокола проверки')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('equipmentSM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipmentSM_att', to='equipment.helpingequipment', verbose_name='ИО')),
            ],
            options={
                'verbose_name': 'Вспомогательное оборудование: проверка характеристик',
                'verbose_name_plural': 'Вспомогательное оборудование: проверка характеристик',
            },
        ),
        migrations.CreateModel(
            name='Attestationequipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата аттестации')),
                ('datedead', models.DateField(blank=True, null=True, verbose_name='Дата окончания аттестации')),
                ('dateorder', models.DateField(blank=True, null=True, verbose_name='Дата заказа следующей аттестации')),
                ('certnumber', models.CharField(blank=True, max_length=90, null=True, verbose_name='Номер аттестата')),
                ('certnumbershort', models.CharField(blank=True, max_length=90, null=True, verbose_name='Краткий номер свидетельства о аттестата')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Стоимость данной аттестации')),
                ('img', models.ImageField(blank=True, null=True, upload_to='user_images', verbose_name='Аттестат')),
                ('statusver', models.CharField(choices=[('Аттестован', 'Аттестован'), ('Признан непригодным', 'Признан непригодным'), ('Спорный', 'Спорный')], default='Аттестован', max_length=300, null=True, verbose_name='Статус')),
                ('place', models.CharField(choices=[('У поверителя', 'У поверителя'), ('На месте эксплуатации', 'На месте эксплуатации')], default='У поверителя', max_length=300, null=True, verbose_name='Место аттестации')),
                ('note', models.CharField(blank=True, max_length=900, null=True, verbose_name='Примечание')),
                ('year', models.CharField(blank=True, max_length=900, null=True, verbose_name='Год аттестации (если нет точных дат)')),
                ('dateordernew', models.DateField(blank=True, null=True, verbose_name='Дата заказа нового оборудования (если аттестовывать не выгодно)')),
                ('haveorder', models.BooleanField(blank=True, default=False, verbose_name='Заказана следующая аттестация (или новое СИ)')),
                ('cust', models.BooleanField(blank=True, default=False, verbose_name='Аттестацию организует Поставщик')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('equipmentSM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipmentSM_att', to='equipment.testingequipment', verbose_name='ИО')),
                ('verificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.verificators', verbose_name='Поверитель')),
                ('verificatorperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.verificatorperson', verbose_name='Поверитель имя')),
            ],
            options={
                'verbose_name': 'Испытательное оборудование: аттестация',
                'verbose_name_plural': 'Испытательное оборудование: аттестации',
            },
        ),
    ]
