# Generated by Django 4.0.4 on 2024-10-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_checkequipment_attestationequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verificationequipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('datedead', models.DateField(blank=True, null=True, verbose_name='Дата окончания поверки')),
                ('dateorder', models.DateField(blank=True, null=True, verbose_name='Дата заказа следующей поверки')),
                ('arshin', models.TextField(blank=True, null=True, verbose_name='Ссылка на сведения о поверке в Аршин')),
                ('certnumber', models.CharField(blank=True, max_length=90, null=True, verbose_name='Номер свидетельства о поверке')),
                ('certnumbershort', models.CharField(blank=True, max_length=90, null=True, verbose_name='Краткий номер свидетельства о поверке')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Стоимость данной поверки')),
                ('img', models.ImageField(blank=True, null=True, upload_to='user_images', verbose_name='Сертификат')),
                ('statusver', models.CharField(choices=[('Поверен', 'Поверен'), ('Признан непригодным', 'Признан непригодным'), ('Спорный', 'Спорный')], default='Поверен', max_length=300, null=True, verbose_name='Статус')),
                ('place', models.CharField(choices=[('У поверителя', 'У поверителя'), ('На месте эксплуатации', 'На месте эксплуатации')], default='У поверителя', max_length=300, null=True, verbose_name='Место поверки')),
                ('note', models.CharField(blank=True, max_length=900, null=True, verbose_name='Примечание')),
                ('year', models.CharField(blank=True, max_length=900, null=True, verbose_name='Год поверки (если нет точных дат)')),
                ('dateordernew', models.DateField(blank=True, null=True, verbose_name='Дата заказа нового оборудования (если поверять не выгодно)')),
                ('haveorder', models.BooleanField(blank=True, default=False, verbose_name='Заказана следующая поверка (или новое СИ)')),
                ('cust', models.BooleanField(blank=True, default=False, verbose_name='Поверку организует Поставщик')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('equipmentSM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipmentSM_ver', to='equipment.measurequipment', verbose_name='СИ')),
                ('verificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.verificators', verbose_name='Поверитель')),
                ('verificatorperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.verificatorperson', verbose_name='Поверитель имя')),
            ],
            options={
                'verbose_name': 'Средство измерения: поверка',
                'verbose_name_plural': 'Средства измерения: поверки',
            },
        ),
    ]
