# Generated by Django 4.0.4 on 2024-10-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_verificationequipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurequipment',
            name='ecard',
        ),
        migrations.RemoveField(
            model_name='measurequipmentcharakters',
            name='aim',
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='aim',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Наименование определяемых (измеряемых) характеристик (параметров) продукции'),
        ),
    ]
