# Generated by Django 4.0.4 on 2024-10-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_remove_measurequipment_ecard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurequipmentcharakters',
            name='aim',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='примечание'),
        ),
    ]
