# Generated by Django 4.0.4 on 2024-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_measurequipmentcharakters_aim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='imginstruction3',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='video',
        ),
        migrations.AddField(
            model_name='equipment',
            name='aim',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Предназначение'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='aim2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование испытуемых групп объектов'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Указатель организации (ИНН_дата добавления ГГММДД)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pravo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Право владения прибором (например, номер и дата накладной)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата внесения записи'),
        ),
    ]
