# Generated by Django 4.0.4 on 2024-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_remove_equipment_imginstruction3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='exnumber',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Внутренний номер'),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('exnumber', 'pointer')},
        ),
    ]
