# Generated by Django 4.0.4 on 2024-10-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_exnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurequipment',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Указатель организации (ИНН_дата добавления ГГММДД)'),
        ),
    ]
