# Generated by Django 4.0.4 on 2024-10-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_company_attestat_alter_company_phone_and_more'),
        ('equipment', '0009_measurequipment_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personchange',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.employees', verbose_name='Ответственный за оборудование'),
        ),
    ]
