# Generated by Django 4.0.4 on 2024-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_personchange_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomnumber',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Номер комнаты'),
        ),
    ]
