# Generated by Django 4.0.4 on 2024-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_rooms_pointer_alter_equipment_pointer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='roomnumber',
            field=models.CharField(default='', max_length=100, verbose_name='Номер комнаты'),
        ),
        migrations.AlterUniqueTogether(
            name='rooms',
            unique_together={('roomnumber', 'pointer')},
        ),
    ]
