# Generated by Django 4.0.4 on 2024-10-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_alter_rooms_roomnumber_alter_rooms_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurequipmentcharakters',
            name='cod',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='виды измерений, тип (группа) средств измерений по МИ 2314'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notemaster',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание (или временное предостережение для сотрудников)'),
        ),
    ]
