# Generated by Django 4.0.4 on 2024-10-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_measurequipmentcharakters_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurequipment',
            name='newcertnumbercal',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Номер последнего сертификата калибровки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newdatecal',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата последнего сертификата калибровки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newdatedeadcal',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата окончания сертификата калибровки'),
        ),
        migrations.CreateModel(
            name='Calibrationequipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата калибровки')),
                ('datedead', models.DateField(blank=True, null=True, verbose_name='Дата окончания калибровки')),
                ('dateorder', models.DateField(blank=True, null=True, verbose_name='Дата заказа следующей калибровки')),
                ('arshin', models.TextField(blank=True, null=True, verbose_name='Ссылка на скан сертификата')),
                ('certnumber', models.CharField(blank=True, max_length=90, null=True, verbose_name='Номер сертификата калибровки')),
                ('certnumbershort', models.CharField(blank=True, max_length=90, null=True, verbose_name='Краткий номер свидетельства о поверке')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Стоимость данной калибровки')),
                ('statusver', models.CharField(choices=[('Калиброван', 'Калиброван'), ('Признан непригодным', 'Признан непригодным'), ('Спорный', 'Спорный')], default='Калиброван', max_length=300, null=True, verbose_name='Статус')),
                ('place', models.CharField(choices=[('У поверителя', 'У поверителя'), ('На месте эксплуатации', 'На месте эксплуатации')], default='У поверителя', max_length=300, null=True, verbose_name='Место калибровки')),
                ('note', models.CharField(blank=True, max_length=900, null=True, verbose_name='Примечание')),
                ('year', models.CharField(blank=True, max_length=900, null=True, verbose_name='Год калибровки (если нет точных дат)')),
                ('dateordernew', models.DateField(blank=True, null=True, verbose_name='Дата заказа нового оборудования (если калибровать не выгодно)')),
                ('haveorder', models.BooleanField(blank=True, default=False, verbose_name='Заказана следующая калибровка (или новое СИ)')),
                ('cust', models.BooleanField(blank=True, default=False, verbose_name='Калибровку организует Поставщик')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('equipmentSM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipmentSM_cal', to='equipment.measurequipment', verbose_name='СИ')),
                ('verificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.verificators', verbose_name='Поверитель')),
                ('verificatorperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.verificatorperson', verbose_name='Поверитель имя')),
            ],
            options={
                'verbose_name': 'Средство измерения: калибровка',
                'verbose_name_plural': 'Средства измерения: калибровка',
            },
        ),
    ]
