# Generated by Django 4.0.4 on 2024-10-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_measurequipment_newcertnumbercal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='equipment1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment1rooms', to='equipment.measurequipment', verbose_name='Барометр'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='equipment2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment2rooms', to='equipment.measurequipment', verbose_name='Гигрометр'),
        ),
    ]
