# Generated by Django 4.0.4 on 2024-10-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_rooms_equipment1_rooms_equipment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteorologicalparameters',
            name='equipment1',
        ),
        migrations.RemoveField(
            model_name='meteorologicalparameters',
            name='equipment2',
        ),
        migrations.RemoveField(
            model_name='meteorologicalparameters',
            name='performer',
        ),
    ]
