# Generated by Django 4.0.4 on 2024-10-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_remove_meteorologicalparameters_equipment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorologicalparameters',
            name='equipments',
            field=models.CharField(blank=True, max_length=190, null=True, verbose_name='СИ'),
        ),
    ]
