# Generated by Django 4.0.4 on 2024-10-31 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_company_caretaker_name_company_caretaker_position_and_more'),
        ('equipment', '0017_meteorologicalparameters_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorologicalparameters',
            name='person',
            field=models.CharField(blank=True, max_length=190, null=True, verbose_name='Исполнитель ФИО'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.employees', verbose_name='Ответственный за комнату'),
        ),
    ]
