# Generated by Django 4.0.4 on 2024-11-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_meteorologicalparameters_person_alter_rooms_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyCard',
        ),
        migrations.RemoveField(
            model_name='verificatorperson',
            name='company',
        ),
        migrations.RemoveField(
            model_name='attestationequipment',
            name='verificatorperson',
        ),
        migrations.RemoveField(
            model_name='calibrationequipment',
            name='verificatorperson',
        ),
        migrations.RemoveField(
            model_name='verificationequipment',
            name='verificatorperson',
        ),
        migrations.AddField(
            model_name='helpingequipment',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации'),
        ),
        migrations.DeleteModel(
            name='ContactsVer',
        ),
        migrations.DeleteModel(
            name='VerificatorPerson',
        ),
    ]
