# Generated by Django 4.0.4 on 2024-11-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_company_caretaker_name_company_caretaker_position_and_more'),
        ('equipment', '0019_delete_companycard_remove_verificatorperson_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurequipment',
            name='newcertnumbercal',
        ),
        migrations.RemoveField(
            model_name='measurequipment',
            name='newdatecal',
        ),
        migrations.RemoveField(
            model_name='measurequipment',
            name='newdatedeadcal',
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewarshin',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на скан сертификата'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewcertnumber',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Номер сертификата калибровки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewcertnumbershort',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Краткий номер свидетельства о поверке'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewcust',
            field=models.BooleanField(blank=True, default=False, verbose_name='Калибровку организует Поставщик'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата калибровки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewdatedead',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания калибровки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewdateorder',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа следующей калибровки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewdateordernew',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа нового оборудования (если калибровать не выгодно)'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewextra',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewhaveorder',
            field=models.BooleanField(blank=True, default=False, verbose_name='Заказана следующая калибровка (или новое СИ)'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewnote',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewplace',
            field=models.CharField(choices=[('У поверителя', 'У поверителя'), ('На месте эксплуатации', 'На месте эксплуатации')], default='У поверителя', max_length=300, null=True, verbose_name='Место калибровки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Стоимость данной калибровки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewstatusver',
            field=models.CharField(default='Калиброван', max_length=300, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewverificator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Поверитель калибровка'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='calnewyear',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Год калибровки (если нет точных дат)'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newarshin',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на сведения о поверке в Аршин'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newcertnumbershort',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Краткий номер свидетельства о поверке'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newcust',
            field=models.BooleanField(blank=True, default=False, verbose_name='Поверку организует Поставщик'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newdateorder',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа следующей поверки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newdateordernew',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа нового оборудования (если поверять не выгодно)'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newextra',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newhaveorder',
            field=models.BooleanField(blank=True, default=False, verbose_name='Заказана следующая поверка (или новое СИ)'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newnote',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.employees', verbose_name='Ответственный за оборудование'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newpersondate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения ответственного'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newplace',
            field=models.CharField(choices=[('У поверителя', 'У поверителя'), ('На месте эксплуатации', 'На месте эксплуатации')], default='У поверителя', max_length=300, null=True, verbose_name='Место поверки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Стоимость данной поверки'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newroomnumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер комнаты'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newroomnumberdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата перемещения'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newstatusver',
            field=models.CharField(default='Поверен', max_length=300, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newverificator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Поверитель поверка'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newyear',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Год поверки (если нет точных дат)'),
        ),
    ]
