# Generated by Django 4.0.4 on 2024-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_remove_measurequipment_newcertnumbercal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurequipment',
            name='newperson',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Ответственный за оборудование'),
        ),
    ]
