# Generated by Django 4.0.4 on 2024-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_alter_measurequipment_newperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurequipment',
            name='calnewdate',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата калибровки'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='calnewdatedead',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата окончания калибровки'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='calnewdateorder',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата заказа следующей калибровки'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='calnewdateordernew',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата заказа нового оборудования (если калибровать не выгодно)'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='newdateorder',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата заказа следующей поверки'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='newdateordernew',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата заказа нового оборудования (если поверять не выгодно)'),
        ),
    ]
