# Generated by Django 4.0.4 on 2024-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_alter_measurequipment_calnewdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurequipment',
            name='newperson',
        ),
        migrations.RemoveField(
            model_name='measurequipment',
            name='newpersondate',
        ),
        migrations.RemoveField(
            model_name='measurequipment',
            name='newroomnumber',
        ),
        migrations.RemoveField(
            model_name='measurequipment',
            name='newroomnumberdate',
        ),
        migrations.AddField(
            model_name='equipment',
            name='newperson',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Ответственный за оборудование'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='newpersondate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения ответственного'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='newroomnumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер комнаты'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='newroomnumberdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата перемещения'),
        ),
    ]
