# Generated by Django 4.0.4 on 2024-11-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_remove_measurequipment_newperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='newpersondate',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата изменения ответственного'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='newroomnumberdate',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Дата перемещения'),
        ),
    ]
