# Generated by Django 4.0.4 on 2024-11-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0024_alter_equipment_newpersondate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurequipment',
            name='calnewdateordernew',
            field=models.CharField(blank=True, default='', max_length=90, null=True, verbose_name='Дата заказа нового оборудования (если калибровать не выгодно)'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='newdateordernew',
            field=models.CharField(blank=True, default='', max_length=90, null=True, verbose_name='Дата заказа нового оборудования (если поверять не выгодно)'),
        ),
    ]
