# Generated by Django 4.0.4 on 2024-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0025_alter_measurequipment_calnewdateordernew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurequipment',
            name='calnewdateordernew',
            field=models.CharField(default='-', max_length=90, verbose_name='Дата заказа нового оборудования (если калибровать не выгодно)'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='newdateordernew',
            field=models.CharField(default='-', max_length=90, verbose_name='Дата заказа нового оборудования (если поверять не выгодно)'),
        ),
    ]
