# Generated by Django 4.0.4 on 2024-11-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0026_alter_measurequipment_calnewdateordernew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurequipment',
            name='calnewdateorder',
            field=models.CharField(blank=True, default='-', max_length=90, null=True, verbose_name='Дата заказа следующей калибровки'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='newdateorder',
            field=models.CharField(blank=True, default='-', max_length=90, null=True, verbose_name='Дата заказа следующей поверки'),
        ),
    ]
