# Generated by Django 4.0.4 on 2024-11-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0027_alter_measurequipment_calnewdateorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceequipmentme',
            options={'verbose_name': 'Средство измерения: Техобслуживание постоянная информация', 'verbose_name_plural': 'Средства измерения: Техобслуживание постоянная информация'},
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='commentservice',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month1',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month10',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month11',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month12',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month2',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month3',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month4',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month5',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month6',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month7',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month8',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentme',
            name='t2month9',
        ),
        migrations.CreateModel(
            name='ServiceEquipmentUME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentservice', models.TextField(default='', verbose_name='Примечание к ТОиР')),
                ('t2month1', models.BooleanField(default=True, verbose_name='ТО 2 в месяце 1')),
                ('t2month2', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 2')),
                ('t2month3', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 3')),
                ('t2month4', models.BooleanField(default=True, verbose_name='ТО 2 в месяце 4')),
                ('t2month5', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 5')),
                ('t2month6', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 6')),
                ('t2month7', models.BooleanField(default=True, verbose_name='ТО 2 в месяце 7')),
                ('t2month8', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 8')),
                ('t2month9', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 9')),
                ('t2month10', models.BooleanField(default=True, verbose_name='ТО 2 в месяце 10')),
                ('t2month11', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 11')),
                ('t2month12', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 12')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Средство измерения: Техобслуживание индивидуальная информация',
                'verbose_name_plural': 'Средства измерения: Техобслуживание индивидуальная информация',
            },
        ),
    ]
