# Generated by Django 4.0.4 on 2024-11-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0028_alter_serviceequipmentme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurequipmentcharakters',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID добавившей организации'),
        ),
    ]
