# Generated by Django 4.0.4 on 2024-11-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0029_measurequipmentcharakters_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceequipmentme',
            name='charakters',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='equipment.measurequipmentcharakters', verbose_name='Характеристики СИ'),
        ),
    ]
