# Generated by Django 4.0.4 on 2024-11-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_serviceequipmentu_delete_serviceequipmentume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceequipmentu',
            options={'verbose_name': 'Оборудование: ТО-2 план', 'verbose_name_plural': 'Оборудование: ТО-2 план'},
        ),
        migrations.AddField(
            model_name='serviceequipmentu',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Год ТО-2 план'),
        ),
        migrations.AlterField(
            model_name='serviceequipmentu',
            name='commentservice',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примечание к ТОиР'),
        ),
        migrations.CreateModel(
            name='ServiceEquipmentUFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год ТО-2 план')),
                ('t2month1', models.BooleanField(default=True, verbose_name='ТО 2 в месяце 1')),
                ('t2month2', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 2')),
                ('t2month3', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 3')),
                ('t2month4', models.BooleanField(default=True, verbose_name='ТО 2 в месяце 4')),
                ('t2month5', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 5')),
                ('t2month6', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 6')),
                ('t2month7', models.BooleanField(default=True, verbose_name='ТО 2 в месяце 7')),
                ('t2month8', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 8')),
                ('t2month9', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 9')),
                ('t2month10', models.BooleanField(default=True, verbose_name='ТО 2 в месяце 10')),
                ('t2month11', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 11')),
                ('t2month12', models.BooleanField(default=False, verbose_name='ТО 2 в месяце 12')),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Оборудование: ТО-2 факт',
                'verbose_name_plural': 'Оборудование: ТО-2 факт',
            },
        ),
    ]
