# Generated by Django 4.0.4 on 2024-11-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0032_alter_serviceequipmentu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceequipmentufact',
            name='pk_pointer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='указатель на pk соответствующего ТО-2 план'),
        ),
    ]
