# Generated by Django 4.0.4 on 2024-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0033_serviceequipmentufact_pk_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceequipmentufact',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Год ТО-2 факт'),
        ),
    ]
