# Generated by Django 4.0.4 on 2024-11-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0034_alter_serviceequipmentufact_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceequipmentufact',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Оборудование'),
        ),
    ]
