# Generated by Django 4.0.4 on 2024-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0036_alter_serviceequipmentu_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingequipment',
            name='newarshin',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на скан аттестата'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newcertnumbershort',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Краткий номер последнего аттестата'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newcust',
            field=models.BooleanField(blank=True, default=False, verbose_name='Аттестацию организует Поставщик'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newdateorder',
            field=models.CharField(blank=True, default='-', max_length=90, null=True, verbose_name='Дата заказа следующей аттестации'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newdateordernew',
            field=models.CharField(default='-', max_length=90, verbose_name='Дата заказа нового оборудования (если аттестация не выгодна)'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newextra',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newhaveorder',
            field=models.BooleanField(blank=True, default=False, verbose_name='Заказана следующая аттестация (или новое ИО)'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newnote',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newplace',
            field=models.CharField(choices=[('У поверителя', 'У поверителя'), ('На месте эксплуатации', 'На месте эксплуатации')], default='У поверителя', max_length=300, null=True, verbose_name='Место аттестации'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Стоимость данной аттестации'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newstatusver',
            field=models.CharField(default='Поверен', max_length=300, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newverificator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Поверитель аттестации'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newyear',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Год аттестации (если нет точных дат)'),
        ),
    ]
