# Generated by Django 4.0.4 on 2024-11-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0037_testingequipment_newarshin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpingequipment',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='measurequipment',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='testingequipment',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Оборудование'),
        ),
    ]
