# Generated by Django 4.0.4 on 2024-11-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0038_alter_helpingequipment_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='pravo_have',
            field=models.CharField(choices=[('собственность', 'собственность'), ('аренда', 'аренда')], default='cобственность', max_length=300, null=True, verbose_name='Собственность или аренда'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='standard_number',
            field=models.CharField(blank=True, default='', max_length=90, null=True, verbose_name='номер в качестве эталона в ФИФ, разряд по ГПС, ЛПС, и т. п.'),
        ),
    ]
