# Generated by Django 4.0.4 on 2024-11-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_company_orderform_and_more'),
        ('equipment', '0039_equipment_pravo_have_equipment_standard_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificators',
            name='head_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кому: имя лица организации-поверителя'),
        ),
        migrations.AddField(
            model_name='verificators',
            name='head_position',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кому: должность лица организации-поверителя'),
        ),
        migrations.CreateModel(
            name='Agreementverification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_agreement_number', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер договора с организацией-поверителем')),
                ('ver_agreement_date', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Дата договора с организацией-поверителем')),
                ('ver_agreement_card', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер учетной карточки у с организации-поверителя')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company', verbose_name='Компания')),
                ('verificator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.verificators', verbose_name='Поверитель')),
            ],
        ),
    ]
