# Generated by Django 4.0.4 on 2024-11-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0040_verificators_head_name_verificators_head_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementverification',
            name='verificator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.verificators', unique=True, verbose_name='Поверитель'),
        ),
    ]
