# Generated by Django 4.0.4 on 2024-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0041_alter_agreementverification_verificator'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementverification',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активный'),
        ),
    ]
