# Generated by Django 4.0.4 on 2024-12-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_company_phone_alter_company_phone_lab_and_more'),
        ('equipment', '0042_agreementverification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementverification',
            name='ver_agreement_card',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер учетной карточки у организации-поверителя'),
        ),
        migrations.CreateModel(
            name='Activaqqchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=False, verbose_name='Активный')),
                ('aqq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.agreementverification', verbose_name='договор с поверителем')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company', verbose_name='Компания')),
            ],
        ),
    ]
