# Generated by Django 4.0.4 on 2024-12-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0043_alter_agreementverification_ver_agreement_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activaqqchange',
        ),
    ]
