# Generated by Django 4.0.4 on 2024-12-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0044_delete_activaqqchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementverification',
            options={'verbose_name': 'Договоры организаций с поверителями', 'verbose_name_plural': 'Договоры организаций с поверителями'},
        ),
        migrations.AddField(
            model_name='agreementverification',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации'),
        ),
    ]
