# Generated by Django 4.0.4 on 2024-12-27 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_company_phone_alter_company_phone_lab_and_more'),
        ('equipment', '0045_alter_agreementverification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activeveraqq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации')),
                ('aqq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.agreementverification', unique=True, verbose_name='Договор с поверителем')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Активный договор с поверителем',
                'verbose_name_plural': 'Активный договор с поверителем',
            },
        ),
    ]
