# Generated by Django 4.0.4 on 2025-01-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0046_activeveraqq'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurequipment',
            name='newdatedead_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания поверки в формате даты'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newdateorder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа следующей поверки в формате даты'),
        ),
        migrations.AddField(
            model_name='measurequipment',
            name='newdateordernew_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа нового оборудования в формате даты'),
        ),
    ]
