# Generated by Django 4.0.4 on 2025-01-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0047_measurequipment_newdatedead_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingequipment',
            name='newdatedead_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания аттестации в формате даты'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newdateorder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа следующей аттестации в формате даты'),
        ),
        migrations.AddField(
            model_name='testingequipment',
            name='newdateordernew_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа нового оборудования в формате даты'),
        ),
    ]
