# Generated by Django 4.0.4 on 2025-01-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0048_testingequipment_newdatedead_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeveraqq',
            name='aqq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.agreementverification', unique=True, verbose_name='Договор с поверителем'),
        ),
    ]
