# Generated by Django 4.0.4 on 2025-01-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0049_alter_activeveraqq_aqq'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementverification',
            name='public_agree',
            field=models.BooleanField(blank=True, default=True, verbose_name='Согласие на передачу данных в Аршин'),
        ),
    ]
