# Generated by Django 4.0.4 on 2025-01-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0051_alter_serviceequipmentu_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceequipmentufact',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Оборудование'),
        ),
    ]
