# Generated by Django 4.0.4 on 2025-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0052_alter_serviceequipmentufact_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationequipment',
            name='arshin',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на скан аттестата'),
        ),
    ]
