# Generated by Django 4.0.4 on 2025-01-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0053_attestationequipment_arshin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceequipmentte',
            options={'verbose_name': 'Испытательное оборудование: Техобслуживание постоянная информация', 'verbose_name_plural': 'Испытательное оборудование: Техобслуживание постоянная информация'},
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='equipment',
        ),
    ]
