# Generated by Django 4.0.4 on 2025-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0054_alter_serviceequipmentte_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpingequipmentcharakters',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID добавившей организации'),
        ),
        migrations.AddField(
            model_name='testingequipmentcharakters',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID добавившей организации'),
        ),
        migrations.AlterField(
            model_name='helpingequipmentcharakters',
            name='kvasyattestation',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='...'),
        ),
    ]
