# Generated by Django 4.0.4 on 2025-01-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0055_helpingequipmentcharakters_pointer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceequipmentte',
            name='charakters',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='equipment.testingequipmentcharakters', verbose_name='Характеристики ИО'),
        ),
    ]
