# Generated by Django 4.0.4 on 2025-01-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0056_alter_serviceequipmentte_charakters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkequipment',
        ),
    ]
