# Generated by Django 4.0.4 on 2025-01-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0057_delete_checkequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='kategory',
            field=models.CharField(choices=[('СИ', 'Средство измерения'), ('ИО', 'Испытательное оборудование'), ('ВО', 'Вспомогательное оборудование')], default='Средство измерения', max_length=300, null=True, verbose_name='Категория'),
        ),
    ]
