# Generated by Django 4.0.4 on 2025-01-23 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0058_alter_equipment_kategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceequipmenthe',
            options={'verbose_name': 'Вспомогательное оборудование: Техобслуживание постоянная информация', 'verbose_name_plural': 'Вспомогательное оборудование: Техобслуживание постоянная информацияк'},
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month1',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month10',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month11',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month12',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month2',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month3',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month4',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month5',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month6',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month7',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month8',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='t2month9',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month1',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month10',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month11',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month12',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month2',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month3',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month4',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month5',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month6',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month7',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month8',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='t2month9',
        ),
        migrations.AlterField(
            model_name='serviceequipmenthe',
            name='charakters',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='equipment.helpingequipmentcharakters', verbose_name='Характеристики ВО'),
        ),
    ]
