# Generated by Django 4.0.4 on 2025-01-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0059_alter_serviceequipmenthe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceequipmenthe',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации кто вносил запись'),
        ),
        migrations.AddField(
            model_name='serviceequipmentme',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации кто вносил запись'),
        ),
        migrations.AddField(
            model_name='serviceequipmentte',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID организации кто вносил запись'),
        ),
    ]
