# Generated by Django 4.0.4 on 2025-01-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0060_serviceequipmenthe_pointer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='commentservice',
        ),
        migrations.RemoveField(
            model_name='serviceequipmenthe',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='serviceequipmentte',
            name='commentservice',
        ),
    ]
