# Generated by Django 4.0.4 on 2025-01-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0061_remove_serviceequipmenthe_commentservice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceequipmenthe',
            options={'verbose_name': 'Вспомогательное оборудование: Техобслуживание постоянная информация', 'verbose_name_plural': 'Вспомогательное оборудование: Техобслуживание постоянная информация'},
        ),
    ]
