# Generated by Django 4.0.4 on 2025-01-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0062_alter_serviceequipmenthe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceequipmenthe',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к постоянным особенностям ТО'),
        ),
        migrations.AddField(
            model_name='serviceequipmentme',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к постоянным особенностям ТО'),
        ),
        migrations.AddField(
            model_name='serviceequipmentte',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к постоянным особенностям ТО'),
        ),
    ]
