# Generated by Django 4.0.4 on 2025-01-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0063_serviceequipmenthe_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='serviceneed',
            field=models.BooleanField(blank=True, default=True, verbose_name='Включать в график ТО'),
        ),
    ]
