# Generated by Django 4.0.4 on 2025-02-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0064_equipment_serviceneed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за комнату'),
        ),
    ]
