# Generated by Django 4.0.4 on 2025-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0067_alter_agreementverification_verificator'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='pointer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID добавившей организации'),
        ),
        migrations.AddField(
            model_name='verificators',
            name='pointer',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='ID добавившей организации'),
        ),
    ]
