# Generated by Django 4.2.19 on 2025-02-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0070_activeveraqq_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpingequipment",
            name="equipment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AlterField(
            model_name="measurequipment",
            name="equipment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AlterField(
            model_name="testingequipment",
            name="equipment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipment",
                verbose_name="Оборудование",
            ),
        ),
    ]
