# Generated by Django 4.2.19 on 2025-02-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0071_alter_helpingequipment_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsequipment",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_images", verbose_name="Фото"
            ),
        ),
    ]
