# Generated by Django 4.2.19 on 2025-02-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0072_alter_commentsequipment_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100, verbose_name="Поверитель")),
            ],
        ),
    ]
