# Generated by Django 4.2.19 on 2025-02-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0074_remove_activeveraqq_created_by_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="helpingequipmentcharakters",
            unique_together={("modificname", "typename", "name", "pointer")},
        ),
        migrations.AlterUniqueTogether(
            name="measurequipmentcharakters",
            unique_together={("reestr", "modificname", "typename", "name", "pointer")},
        ),
        migrations.AlterUniqueTogether(
            name="testingequipmentcharakters",
            unique_together={("modificname", "typename", "name", "pointer")},
        ),
    ]
