# Generated by Django 4.2.19 on 2025-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0075_alter_helpingequipmentcharakters_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="expresstest",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Возможно тестирование (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="needsetplace",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Требуется установка (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="power",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Работает от сети (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="expresstest",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Возможно тестирование  (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="needsetplace",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Требуется установка (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="power",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Работает от сети (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="expresstest",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Возможно тестирование  (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="needsetplace",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Требуется установка (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="power",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Работает от сети (да - "1", нет - "0")',
            ),
        ),
    ]
