# Generated by Django 4.2.19 on 2025-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0076_alter_helpingequipmentcharakters_expresstest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="complectlist",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Где указана комплектация оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="complectlist",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Где указана комплектация оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="complectlist",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Где указана комплектация оборудования",
            ),
        ),
    ]
