# Generated by Django 4.2.19 on 2025-03-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0077_alter_helpingequipmentcharakters_complectlist_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testingequipmentcharakters",
            old_name="aim",
            new_name="analises_types",
        ),
        migrations.RenameField(
            model_name="testingequipmentcharakters",
            old_name="aim2",
            new_name="analited_objects",
        ),
        migrations.RenameField(
            model_name="testingequipmentcharakters",
            old_name="measurydiapason",
            new_name="main_technical_characteristics",
        ),
    ]
