# Generated by Django 4.2.19 on 2025-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipment",
            "0078_rename_aim_testingequipmentcharakters_analises_types_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testingequipmentcharakters",
            name="aim",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="примечание"
            ),
        ),
    ]
