# Generated by Django 4.2.19 on 2025-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0079_testingequipmentcharakters_aim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helpingequipmentcharakters",
            name="kvasyattestation",
        ),
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="aim",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="примечание"
            ),
        ),
    ]
