# Generated by Django 4.2.19 on 2025-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipment",
            "0080_remove_helpingequipmentcharakters_kvasyattestation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="expresstest",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Возможно тестирование  (да - "1", нет - "0")',
            ),
        ),
    ]
