# Generated by Django 4.2.19 on 2025-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0081_alter_helpingequipmentcharakters_expresstest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="helpingequipmentcharakters",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="measurequipmentcharakters",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="testingequipmentcharakters",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="aim",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="aim2",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="invnumber",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Инвентарный номер (присваивает бухгалтерия)",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="kategory",
            field=models.CharField(
                choices=[
                    ("СИ", "Средство измерения"),
                    ("ИО", "Испытательное оборудование"),
                    ("ВО", "Вспомогательное оборудование"),
                ],
                default="Средство измерения",
                max_length=300,
                null=True,
                verbose_name='Категория: указать "СИ", "ИО" или "ВО"',
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="new",
            field=models.CharField(
                default="новый",
                max_length=100,
                verbose_name='Новый или б/у (указать: "новый" или "б/у"',
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="newperson",
            field=models.CharField(
                blank=True,
                max_length=90,
                null=True,
                verbose_name='Ответственный за оборудование (краткое ФИО сотрудника, например: "И.И.Иванов")',
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="pravo_have",
            field=models.CharField(
                choices=[("собственность", "собственность"), ("аренда", "аренда")],
                default="cобственность",
                max_length=300,
                null=True,
                verbose_name='Право владения прибором: указать "cобственность" или "аренда"',
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serviceneed",
            field=models.BooleanField(
                blank=True,
                default=True,
                verbose_name='Включать в график ТО (да - "1", нет - "0")',
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Э", "Экс."),
                    ("РЕ", "Рем."),
                    ("С", "Сп."),
                    ("Р", "Рез."),
                    ("Д", "Др."),
                ],
                default="В эксплуатации",
                max_length=300,
                null=True,
                verbose_name='Статус: указать "Э" - эксплуатация, "РЕ" - ремонт, "Р" - резерв, "Д" - другое',
            ),
        ),
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="typename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Тип/модификация",
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="typename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Тип/модификация",
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="typename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Тип/модификация",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="helpingequipmentcharakters",
            unique_together={("typename", "name", "pointer")},
        ),
        migrations.AlterUniqueTogether(
            name="measurequipmentcharakters",
            unique_together={("reestr", "typename", "name", "pointer")},
        ),
        migrations.AlterUniqueTogether(
            name="testingequipmentcharakters",
            unique_together={("typename", "name", "pointer")},
        ),
        migrations.RemoveField(
            model_name="helpingequipmentcharakters",
            name="modificname",
        ),
        migrations.RemoveField(
            model_name="measurequipmentcharakters",
            name="modificname",
        ),
        migrations.RemoveField(
            model_name="testingequipmentcharakters",
            name="modificname",
        ),
    ]
