# Generated by Django 4.2.19 on 2025-03-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0082_alter_helpingequipmentcharakters_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="measurequipmentcharakters",
            unique_together=set(),
        ),
    ]
