# Generated by Django 4.2.19 on 2025-03-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0083_alter_measurequipmentcharakters_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="helpingequipmentcharakters",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="testingequipmentcharakters",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="measurequipmentcharakters",
            unique_together={("reestr", "typename", "name", "pointer")},
        ),
    ]
