# Generated by Django 4.2.19 on 2025-03-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0084_alter_helpingequipmentcharakters_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="helpingequipmentcharakters",
            unique_together={("typename", "name", "pointer")},
        ),
        migrations.AlterUniqueTogether(
            name="testingequipmentcharakters",
            unique_together={("typename", "name", "pointer")},
        ),
    ]
