# Generated by Django 4.2.19 on 2025-03-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0085_alter_helpingequipmentcharakters_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.manufacturer",
                verbose_name="Название компании-производителя",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="new",
            field=models.CharField(
                default="новый",
                max_length=100,
                verbose_name='Новый или б/у (указать: "новый" или "б/у")',
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="pravo_have",
            field=models.CharField(
                choices=[("собственность", "собственность"), ("аренда", "аренда")],
                default="cобственность",
                max_length=300,
                null=True,
                verbose_name='Указать "cобственность" или "аренда"',
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serviceneed",
            field=models.BooleanField(
                blank=True,
                default=True,
                verbose_name='Включать в график ТО при автоформировании графика на год (да - "1", нет - "0")',
            ),
        ),
    ]
