# Generated by Django 4.2.19 on 2025-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0086_alter_equipment_manufacturer_alter_equipment_new_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="yearintoservice",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=4,
                null=True,
                verbose_name="Год ввода в эксплуатацию",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="yearmanuf",
            field=models.CharField(
                blank=True,
                default="",
                max_length=4,
                null=True,
                verbose_name="Год выпуска",
            ),
        ),
    ]
