# Generated by Django 4.2.19 on 2025-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0087_alter_equipment_yearintoservice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="yearintoservice",
            field=models.IntegerField(
                blank=True,
                default="0",
                null=True,
                verbose_name="Год ввода в эксплуатацию",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="yearmanuf",
            field=models.IntegerField(
                blank=True, default="", null=True, verbose_name="Год выпуска"
            ),
        ),
    ]
