# Generated by Django 4.2.19 on 2025-03-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0088_alter_equipment_yearintoservice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activeveraqq",
            options={
                "verbose_name": "Контрагенты: Договор с поверителем активный",
                "verbose_name_plural": "Контрагенты: Договор с поверителем активный",
            },
        ),
        migrations.AlterModelOptions(
            name="agreementverification",
            options={
                "verbose_name": "Контрагенты: Договоры с поверителями",
                "verbose_name_plural": "Контрагенты: Договоры с поверителями",
            },
        ),
        migrations.AlterModelOptions(
            name="attestationequipment",
            options={
                "verbose_name": "ИО метрология аттестация",
                "verbose_name_plural": "ИО метрология аттестация",
            },
        ),
        migrations.AlterModelOptions(
            name="calibrationequipment",
            options={
                "verbose_name": "СИ метрология калибровка",
                "verbose_name_plural": "СИ метрология калибровка",
            },
        ),
        migrations.AlterModelOptions(
            name="commentsattestationequipment",
            options={
                "verbose_name": "ИО Комментарий к аттестации",
                "verbose_name_plural": "ИО Комментарий к аттестации",
            },
        ),
        migrations.AlterModelOptions(
            name="commentsequipment",
            options={
                "verbose_name": "ЛО записи в карточках",
                "verbose_name_plural": "ЛО записи в карточках",
            },
        ),
        migrations.AlterModelOptions(
            name="commentsverificationequipment",
            options={
                "verbose_name": "СИ Комментарий к поверке",
                "verbose_name_plural": "СИ Комментарий к поверке",
            },
        ),
        migrations.AlterModelOptions(
            name="docscons",
            options={
                "verbose_name": "ЛО комплект к прибору",
                "verbose_name_plural": "ЛО комплекты к приборам",
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "ЛО список", "verbose_name_plural": "ЛО список"},
        ),
        migrations.AlterModelOptions(
            name="helpingequipment",
            options={
                "ordering": ["charakters__name"],
                "verbose_name": "ВО список",
                "verbose_name_plural": "ВО список",
            },
        ),
        migrations.AlterModelOptions(
            name="helpingequipmentcharakters",
            options={
                "verbose_name": "ВО характеристики",
                "verbose_name_plural": "ВО характеристики",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "verbose_name": "Контрагенты: Производитель",
                "verbose_name_plural": "Контрагенты: Производители",
            },
        ),
        migrations.AlterModelOptions(
            name="measurequipment",
            options={
                "ordering": ["charakters__name"],
                "verbose_name": "СИ список",
                "verbose_name_plural": "СИ список",
            },
        ),
        migrations.AlterModelOptions(
            name="measurequipmentcharakters",
            options={
                "verbose_name": "СИ характеристики",
                "verbose_name_plural": "СИ характеристики",
            },
        ),
        migrations.AlterModelOptions(
            name="meteorologicalparameters",
            options={
                "verbose_name": "Микроклимат: записи",
                "verbose_name_plural": "Микроклимат: записи",
            },
        ),
        migrations.AlterModelOptions(
            name="personchange",
            options={
                "verbose_name": "Принадлежность: изменение ответственного",
                "verbose_name_plural": "Принадлежность: изменение ответственного",
            },
        ),
        migrations.AlterModelOptions(
            name="rooms",
            options={
                "verbose_name": "Принадлежность: список комнат",
                "verbose_name_plural": "Принадлежность: список комнат",
            },
        ),
        migrations.AlterModelOptions(
            name="roomschange",
            options={
                "verbose_name": "Принадлежность: изменение комнаты",
                "verbose_name_plural": "Принадлежность: изменение комнаты",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceequipmenthe",
            options={
                "verbose_name": "ТО ВО постоянная информация",
                "verbose_name_plural": "ТО ВО постоянная информация",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceequipmentme",
            options={
                "verbose_name": "ТО СИ постоянная информация",
                "verbose_name_plural": "ТО СИ постоянная информация",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceequipmentte",
            options={
                "verbose_name": "ТО ИО постоянная информация",
                "verbose_name_plural": "ТО ИО постоянная информация",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceequipmentu",
            options={
                "verbose_name": "ТО ЛО: ТО-2 план",
                "verbose_name_plural": "ТО ЛО: ТО-2 план",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceequipmentufact",
            options={
                "verbose_name": "ТО ЛО: ТО-2 факт",
                "verbose_name_plural": "ТО ЛО: ТО-2 факт",
            },
        ),
        migrations.AlterModelOptions(
            name="testingequipment",
            options={
                "ordering": ["charakters__name"],
                "verbose_name": "ИО список",
                "verbose_name_plural": "ИО список",
            },
        ),
        migrations.AlterModelOptions(
            name="testingequipmentcharakters",
            options={
                "verbose_name": "ИО характеристики",
                "verbose_name_plural": "ИО характеристики",
            },
        ),
        migrations.AlterModelOptions(
            name="verificationequipment",
            options={
                "verbose_name": "СИ метрология поверка",
                "verbose_name_plural": "СИ метрология поверка",
            },
        ),
        migrations.AlterModelOptions(
            name="verificators",
            options={
                "verbose_name": "Контрагенты: Поверитель",
                "verbose_name_plural": "Контрагенты: Поверители",
            },
        ),
    ]
