# Generated by Django 4.2.19 on 2025-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0089_alter_activeveraqq_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default="0",
                max_digits=100,
                null=True,
                verbose_name="Стоимость",
            ),
        ),
    ]
