# Generated by Django 4.2.19 on 2025-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0090_alter_equipment_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default="0",
                max_digits=100,
                null=True,
                verbose_name='Стоимость (укажите "0" если стоимость неизвестна)',
            ),
        ),
    ]
