# Generated by Django 4.2.19 on 2025-03-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0091_alter_equipment_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="equipment",
            unique_together={("exnumber", "pointer", "lot")},
        ),
    ]
