# Generated by Django 4.2.19 on 2025-03-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0094_rooms_created_by_rooms_updated_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="equipment",
            unique_together={("pointer", "lot")},
        ),
    ]
