# Generated by Django 4.2.19 on 2025-03-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0095_alter_equipment_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="equipment",
            unique_together={("pointer", "lot", "manufacturer", "yearmanuf")},
        ),
    ]
