# Generated by Django 4.2.19 on 2025-03-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0096_alter_equipment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personchange",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="roomschange",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipment",
                verbose_name="Оборудование",
            ),
        ),
    ]
