# Generated by Django 4.2.19 on 2025-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0097_alter_personchange_equipment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationequipment",
            name="certnumbershort",
        ),
        migrations.AlterField(
            model_name="verificationequipment",
            name="cust",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Поверку организует Поставщик: "1" - да, "0" - нет',
            ),
        ),
        migrations.AlterField(
            model_name="verificationequipment",
            name="extra",
            field=models.TextField(
                blank=True, null=True, verbose_name="Выписка из сведений о поверке"
            ),
        ),
        migrations.AlterField(
            model_name="verificationequipment",
            name="haveorder",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Заказана следующая поверка (или новое СИ): "1" - заказана, "0" - не заказана',
            ),
        ),
        migrations.AlterField(
            model_name="verificationequipment",
            name="place",
            field=models.CharField(
                choices=[
                    ("У поверителя", "У поверителя"),
                    ("На месте эксплуатации", "На месте эксплуатации"),
                ],
                default="У поверителя",
                max_length=300,
                null=True,
                verbose_name='Место поверки: выберите "У поверителя", "На месте эксплуатации"',
            ),
        ),
        migrations.AlterField(
            model_name="verificationequipment",
            name="statusver",
            field=models.CharField(
                choices=[
                    ("Поверен", "Поверен"),
                    ("Признан непригодным", "Признан непригодным"),
                    ("Спорный", "Спорный"),
                ],
                default="Поверен",
                max_length=300,
                null=True,
                verbose_name='Статус поверки: выберите "Поверен", "Признан непригодным", "Спорный"',
            ),
        ),
    ]
