# Generated by Django 4.2.19 on 2025-03-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0098_remove_verificationequipment_certnumbershort_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationequipment",
            name="verificator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.verificators",
                verbose_name="Название компании поверителя",
            ),
        ),
    ]
