# Generated by Django 4.2.19 on 2025-03-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0099_alter_verificationequipment_verificator"),
    ]

    operations = [
        migrations.AddField(
            model_name="attestationequipment",
            name="pointer",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="ID организации"
            ),
        ),
        migrations.AddField(
            model_name="calibrationequipment",
            name="pointer",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="ID организации"
            ),
        ),
        migrations.AddField(
            model_name="verificationequipment",
            name="pointer",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="ID организации"
            ),
        ),
    ]
