# Generated by Django 4.2.19 on 2025-03-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0100_attestationequipment_pointer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attestationequipment",
            name="certnumbershort",
        ),
        migrations.RemoveField(
            model_name="calibrationequipment",
            name="certnumbershort",
        ),
        migrations.RemoveField(
            model_name="measurequipment",
            name="calnewcertnumbershort",
        ),
        migrations.RemoveField(
            model_name="measurequipment",
            name="newcertnumbershort",
        ),
        migrations.RemoveField(
            model_name="testingequipment",
            name="newcertnumbershort",
        ),
    ]
