# Generated by Django 4.2.19 on 2025-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0101_remove_attestationequipment_certnumbershort_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestationequipment",
            name="arshin",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Ссылка на скан аттестата",
            ),
        ),
        migrations.AlterField(
            model_name="calibrationequipment",
            name="arshin",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Ссылка на скан сертификата",
            ),
        ),
        migrations.AlterField(
            model_name="verificationequipment",
            name="arshin",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Ссылка на сведения о поверке в Аршин",
            ),
        ),
    ]
