# Generated by Django 4.2.19 on 2025-03-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0102_alter_attestationequipment_arshin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestationequipment",
            name="cust",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Аттестацию организует Поставщик: "1" - да, "0" - нет',
            ),
        ),
        migrations.AlterField(
            model_name="attestationequipment",
            name="extra",
            field=models.TextField(
                blank=True, null=True, verbose_name="Выписка из аттестата"
            ),
        ),
        migrations.AlterField(
            model_name="attestationequipment",
            name="haveorder",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Заказана следующая аттестация (или новое ИО): "1" - заказана, "0" - не заказана',
            ),
        ),
        migrations.AlterField(
            model_name="attestationequipment",
            name="place",
            field=models.CharField(
                choices=[
                    ("У поверителя", "У поверителя"),
                    ("На месте эксплуатации", "На месте эксплуатации"),
                ],
                default="У поверителя",
                max_length=300,
                null=True,
                verbose_name='Место аттестации: выберите "У поверителя", "На месте эксплуатации"',
            ),
        ),
        migrations.AlterField(
            model_name="attestationequipment",
            name="statusver",
            field=models.CharField(
                choices=[
                    ("Аттестован", "Аттестован"),
                    ("Признан непригодным", "Признан непригодным"),
                    ("Спорный", "Спорный"),
                ],
                default="Аттестован",
                max_length=300,
                null=True,
                verbose_name='Статус аттестации: выберите "Аттестован", "Признан непригодным", "Спорный"',
            ),
        ),
        migrations.AlterField(
            model_name="attestationequipment",
            name="verificator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.verificators",
                verbose_name="Название компании поверителя",
            ),
        ),
        migrations.AlterField(
            model_name="calibrationequipment",
            name="cust",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Калибровку организует Поставщик: "1" - да, "0" - нет',
            ),
        ),
        migrations.AlterField(
            model_name="calibrationequipment",
            name="extra",
            field=models.TextField(
                blank=True, null=True, verbose_name="Выписка из сертификата калибровки"
            ),
        ),
        migrations.AlterField(
            model_name="calibrationequipment",
            name="haveorder",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Заказана следующая калибровка (или новое СИ): "1" - заказана, "0" - не заказана',
            ),
        ),
        migrations.AlterField(
            model_name="calibrationequipment",
            name="statusver",
            field=models.CharField(
                choices=[
                    ("Калиброван", "Калиброван"),
                    ("Признан непригодным", "Признан непригодным"),
                    ("Спорный", "Спорный"),
                ],
                default="Калиброван",
                max_length=300,
                null=True,
                verbose_name='Статус калибровки: выберите "Калиброван", "Признан непригодным", "Спорный"',
            ),
        ),
        migrations.AlterField(
            model_name="calibrationequipment",
            name="verificator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.verificators",
                verbose_name="Название компании поверителя",
            ),
        ),
    ]
