# Generated by Django 4.2.19 on 2025-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0103_alter_attestationequipment_cust_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationequipment",
            name="place",
            field=models.CharField(
                choices=[
                    ("У поверителя", "У поверителя"),
                    ("На месте эксплуатации", "На месте эксплуатации"),
                ],
                default="У поверителя",
                max_length=300,
                null=True,
                verbose_name='Место калибровки: выберите "У поверителя", "На месте эксплуатации"',
            ),
        ),
    ]
