# Generated by Django 4.2.19 on 2025-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0104_alter_calibrationequipment_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationequipment",
            name="haveorder",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name='Заказана следующая калибровки (или новое СИ): "1" - заказана, "0" - не заказана',
            ),
        ),
    ]
