# Generated by Django 4.2.19 on 2025-03-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0105_alter_calibrationequipment_haveorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="aim",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Виды испытаний и характеристики продукции",
            ),
        ),
    ]
