# Generated by Django 4.2.19 on 2025-04-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_company_payement_date"),
        ("equipment", "0106_equipment_aim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeveraqq",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="agreementverification",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
                verbose_name="Компания",
            ),
        ),
    ]
