# Generated by Django 4.2.19 on 2025-04-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0107_alter_activeveraqq_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeveraqq",
            name="aqq",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.agreementverification",
                unique=True,
                verbose_name="Договор с поверителем",
            ),
        ),
    ]
