# Generated by Django 4.2.19 on 2025-04-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0108_alter_activeveraqq_aqq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="helpingequipmentcharakters",
            old_name="aim",
            new_name="note",
        ),
        migrations.RemoveField(
            model_name="testingequipmentcharakters",
            name="analises_types",
        ),
        migrations.RemoveField(
            model_name="testingequipmentcharakters",
            name="analited_objects",
        ),
        migrations.AddField(
            model_name="helpingequipment",
            name="aim",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Назначение"
            ),
        ),
        migrations.AddField(
            model_name="testingequipment",
            name="analises_types",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Наименование видов испытаний и/или определяемых характеристик (параметров) продукции",
            ),
        ),
        migrations.AddField(
            model_name="testingequipment",
            name="analited_objects",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Наименование испытуемых групп объектов",
            ),
        ),
    ]
