# Generated by Django 4.2.19 on 2025-04-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0109_rename_aim_helpingequipmentcharakters_note_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testingequipment",
            old_name="analises_types",
            new_name="aim",
        ),
    ]
