# Generated by Django 4.2.19 on 2025-04-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0110_rename_analises_types_testingequipment_aim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="aim",
        ),
    ]
