# Generated by Django 4.2.19 on 2025-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0111_remove_equipment_aim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="name",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Название прибора"
            ),
        ),
        migrations.AlterField(
            model_name="helpingequipmentcharakters",
            name="typename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1000,
                null=True,
                verbose_name="Тип/модификация",
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="name",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Название прибора"
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="typename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1000,
                null=True,
                verbose_name="Тип/модификация",
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="name",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Название прибора"
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="typename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1000,
                null=True,
                verbose_name="Тип/модификация",
            ),
        ),
    ]
