# Generated by Django 4.2.19 on 2025-04-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0112_alter_helpingequipmentcharakters_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="yearintoservice",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Год ввода в эксплуатацию",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="yearmanuf",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Год выпуска"
            ),
        ),
    ]
