# Generated by Django 4.2.19 on 2025-04-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0113_alter_equipment_yearintoservice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="lot",
            field=models.CharField(
                default="", max_length=10000, verbose_name="Заводской номер"
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="name",
            field=models.CharField(
                default="", max_length=10000, verbose_name="Название прибора"
            ),
        ),
        migrations.AlterField(
            model_name="measurequipmentcharakters",
            name="reestr",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10000,
                null=True,
                verbose_name="Номер в Госреестре",
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="name",
            field=models.CharField(
                default="", max_length=10000, verbose_name="Название прибора"
            ),
        ),
        migrations.AlterField(
            model_name="testingequipmentcharakters",
            name="typename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10000,
                null=True,
                verbose_name="Тип/модификация",
            ),
        ),
    ]
