# Generated by Django 4.2.19 on 2025-04-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0114_alter_equipment_lot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="companyAdress",
            field=models.CharField(
                blank=True, default="", max_length=20000, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="companyName",
            field=models.CharField(
                max_length=10000, unique=True, verbose_name="Производитель"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.CharField(
                blank=True, default="Россия", max_length=20000, verbose_name="Страна"
            ),
        ),
    ]
