# Generated by Django 4.2.19 on 2025-04-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0115_alter_manufacturer_companyadress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meteorologicalparameters",
            name="equipments",
            field=models.CharField(
                blank=True, max_length=10000, null=True, verbose_name="СИ"
            ),
        ),
    ]
