# Generated by Django 4.2.19 on 2025-04-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0116_alter_meteorologicalparameters_equipments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestationequipment",
            name="verificator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.verificators",
                verbose_name="Название компании поверителя",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calibrationequipment",
            name="verificator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.verificators",
                verbose_name="Название компании поверителя",
            ),
        ),
        migrations.AlterField(
            model_name="verificationequipment",
            name="verificator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.verificators",
                verbose_name="Название компании поверителя",
            ),
        ),
    ]
