# Generated by Django 4.2.19 on 2026-02-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0117_alter_attestationequipment_verificator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeveraqq",
            name="aqq",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.agreementverification",
                verbose_name="Договор с поверителем",
            ),
        ),
    ]
