# Generated by Django 4.0.4 on 2024-10-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=10000, verbose_name='Заголовок')),
                ('metatitle', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Метазаголовок страницы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Метаописание страницы')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('text', models.TextField(verbose_name='Текст записи.')),
            ],
            options={
                'verbose_name': 'О лабораторном оборудовании',
                'verbose_name_plural': 'О лабораторном оборудовании',
            },
        ),
    ]
