# Generated by Django 4.0.4 on 2024-10-11 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.TextField(default='', verbose_name='Текст объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата новости')),
                ('text', models.TextField(default='', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('text', models.TextField(default='', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ResultValueJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания журнала')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Наименование журнала')),
                ('for_url', models.CharField(default='', max_length=100, verbose_name='Адрес журнала')),
                ('CM', models.TextField(blank=True, null=True, verbose_name='для проб')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Доп')),
            ],
            options={
                'verbose_name': 'Журнал результатов измерений',
                'verbose_name_plural': 'Журналы результатов измерений',
            },
        ),
        migrations.CreateModel(
            name='AttestationJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания журнала')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Наименование журнала')),
                ('ndocument', models.CharField(default='', max_length=100, verbose_name='Методы испытаний')),
                ('for_url', models.CharField(default='', max_length=100, verbose_name='Адрес журнала')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Доп')),
                ('str_html', models.TextField(blank=True, null=True, verbose_name='HTML код для страницы журнала')),
                ('formuls', models.TextField(blank=True, null=True, verbose_name='Формулы для расчётов')),
                ('img', models.ImageField(default='user_images/default.png', upload_to='user_images', verbose_name='Картинка для журнала')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный за ведение журнала')),
            ],
            options={
                'verbose_name': 'Журнал измерений',
                'verbose_name_plural': 'Журналы измерений',
            },
        ),
    ]
