# Generated by Django 4.0.4 on 2024-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Текст записи')),
            ],
            options={
                'verbose_name': 'О регистрации',
                'verbose_name_plural': 'О регистрации',
            },
        ),
    ]
