# Generated by Django 4.0.4 on 2024-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Текст записи')),
            ],
            options={
                'verbose_name': 'О сайте',
                'verbose_name_plural': 'О сайте',
            },
        ),
    ]
