# Generated by Django 4.2.19 on 2025-03-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0002_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                ("text", models.TextField(verbose_name="Текст записи")),
            ],
            options={
                "verbose_name": "Мануал по работе на сайте",
                "verbose_name_plural": "Мануал по работе на сайте",
            },
        ),
    ]
