# Generated by Django 4.2.19 on 2025-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0003_manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                ("text", models.TextField(verbose_name="Текст записи")),
            ],
            options={
                "verbose_name": "Договор-оферта",
                "verbose_name_plural": "Договор-оферта",
            },
        ),
        migrations.CreateModel(
            name="PolitycaConfident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                ("text", models.TextField(verbose_name="Текст записи")),
            ],
        ),
    ]
