# Generated by Django 4.2.19 on 2025-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inorganiclaw",
            name="examples",
            field=models.TextField(blank=True, null=True, verbose_name="Примеры"),
        ),
        migrations.AddField(
            model_name="inorganiclaw",
            name="exceptions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание исключений"
            ),
        ),
        migrations.AddField(
            model_name="inorganiclaw",
            name="formula",
            field=models.TextField(
                blank=True, null=True, verbose_name="Общая формула закона"
            ),
        ),
        migrations.AddField(
            model_name="inorganiclaw",
            name="img1",
            field=models.ImageField(
                blank=True,
                default="user_images/default1.png",
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация1",
            ),
        ),
        migrations.AddField(
            model_name="inorganiclaw",
            name="img2",
            field=models.ImageField(
                blank=True,
                default="user_images/default1.png",
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация2",
            ),
        ),
        migrations.AddField(
            model_name="inorganiclaw",
            name="img3",
            field=models.ImageField(
                blank=True,
                default="user_images/default1.png",
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация3",
            ),
        ),
        migrations.AddField(
            model_name="inorganiclaw",
            name="number",
            field=models.TextField(blank=True, null=True, verbose_name="Номер закона"),
        ),
        migrations.AddField(
            model_name="inorganiclaw",
            name="trening",
            field=models.TextField(blank=True, null=True, verbose_name="Тренировка"),
        ),
        migrations.AlterField(
            model_name="inorganiclaw",
            name="text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание закона"
            ),
        ),
        migrations.AlterField(
            model_name="inorganiclaw",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Заголовок"),
        ),
    ]
