# Generated by Django 4.2.19 on 2025-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0002_inorganiclaw_examples_inorganiclaw_exceptions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inorganiclaw",
            name="img1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация1",
            ),
        ),
        migrations.AlterField(
            model_name="inorganiclaw",
            name="img2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация2",
            ),
        ),
        migrations.AlterField(
            model_name="inorganiclaw",
            name="img3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация3",
            ),
        ),
        migrations.AlterField(
            model_name="inorganiclaw",
            name="number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Номер закона"
            ),
        ),
    ]
