# Generated by Django 4.2.19 on 2025-12-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0003_alter_inorganiclaw_img1_alter_inorganiclaw_img2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InorganicReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "metatitle",
                    models.CharField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="Метазаголовок страницы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Метаописание страницы"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "reagent1",
                    models.CharField(blank=True, null=True, verbose_name="Реагент1"),
                ),
                (
                    "reagent2",
                    models.CharField(blank=True, null=True, verbose_name="Реагент2"),
                ),
                (
                    "reagent3",
                    models.CharField(blank=True, null=True, verbose_name="Реагент3"),
                ),
                (
                    "product1",
                    models.CharField(blank=True, null=True, verbose_name="Продукт1"),
                ),
                (
                    "product2",
                    models.CharField(blank=True, null=True, verbose_name="Продукт1"),
                ),
                (
                    "product3",
                    models.CharField(blank=True, null=True, verbose_name="Продукт1"),
                ),
                (
                    "product4",
                    models.CharField(blank=True, null=True, verbose_name="Продукт1"),
                ),
                (
                    "number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Chem.inorganiclaw",
                        verbose_name="Закон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реакция неорганической химии",
                "verbose_name_plural": "Реакции неорганической химии",
            },
        ),
    ]
