# Generated by Django 4.2.19 on 2025-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0004_inorganicreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="inorganicreaction",
            name="condition",
            field=models.CharField(
                blank=True, null=True, verbose_name="Условия реакции"
            ),
        ),
    ]
