# Generated by Django 4.2.19 on 2025-12-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0005_inorganicreaction_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="inorganicreaction",
            name="video",
            field=models.CharField(
                blank=True, null=True, verbose_name="Ссылка на видео"
            ),
        ),
        migrations.AlterField(
            model_name="inorganicreaction",
            name="condition",
            field=models.CharField(
                blank=True,
                default="нормальные условия",
                null=True,
                verbose_name="Условия реакции",
            ),
        ),
    ]
