# Generated by Django 4.2.19 on 2025-12-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0006_inorganicreaction_video_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inorganicreaction",
            unique_together={("reagent1", "reagent2", "reagent3", "condition")},
        ),
    ]
