# Generated by Django 4.2.19 on 2025-12-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0007_alter_inorganicreaction_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inorganicreaction",
            unique_together={
                ("reagent1", "reagent2", "reagent3", "condition", "number")
            },
        ),
    ]
