# Generated by Django 4.2.19 on 2025-12-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0008_alter_inorganicreaction_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="inorganicreaction",
            name="extra",
            field=models.CharField(
                blank=True, null=True, verbose_name="Дополнительная информация"
            ),
        ),
    ]
