# Generated by Django 4.2.19 on 2025-12-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0009_inorganicreaction_extra"),
    ]

    operations = [
        migrations.CreateModel(
            name="NamesCompaunds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        unique=True,
                        verbose_name="Формула",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Все названия этого соединения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Название химического вещества",
                "verbose_name_plural": "Названия химических веществ",
            },
        ),
    ]
