# Generated by Django 4.2.19 on 2025-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0010_namescompaunds"),
    ]

    operations = [
        migrations.AddField(
            model_name="inorganicreaction",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("ОГЭ", "ОГЭ"), ("ЕГЭ", "ЕГЭ")],
                default="ОГЭ",
                null=True,
                verbose_name="Уровень",
            ),
        ),
    ]
