# Generated by Django 4.2.19 on 2025-12-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0011_inorganicreaction_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="namescompaunds",
            name="appearance",
            field=models.TextField(blank=True, null=True, verbose_name="Внешний вид"),
        ),
    ]
