# Generated by Django 4.2.19 on 2026-01-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0012_namescompaunds_appearance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atomlaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "metatitle",
                    models.CharField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="Метазаголовок страницы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Метаописание страницы"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Номер закона"
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Заголовок"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание закона"
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True, null=True, verbose_name="Общая формула закона"
                    ),
                ),
                (
                    "examples",
                    models.TextField(blank=True, null=True, verbose_name="Примеры"),
                ),
                (
                    "exceptions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание исключений"
                    ),
                ),
                (
                    "trening",
                    models.TextField(blank=True, null=True, verbose_name="Тренировка"),
                ),
                (
                    "img1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация1",
                    ),
                ),
                (
                    "img2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация2",
                    ),
                ),
                (
                    "img3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация3",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtomTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "metatitle",
                    models.CharField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="Метазаголовок страницы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Метаописание страницы"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "text",
                    models.CharField(blank=True, null=True, verbose_name="Вопрос"),
                ),
                (
                    "answer",
                    models.CharField(blank=True, null=True, verbose_name="Ответ"),
                ),
                (
                    "number",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Chem.atomlaw",
                        verbose_name="Закон",
                    ),
                ),
            ],
        ),
    ]
