# Generated by Django 4.2.19 on 2026-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0013_atomlaw_atomtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="atomtest",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("ОГЭ", "ОГЭ"), ("ЕГЭ", "ЕГЭ")],
                default="ЕГЭ",
                null=True,
                verbose_name="Уровень",
            ),
        ),
    ]
