# Generated by Django 4.2.19 on 2026-01-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0014_atomtest_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atomlaw",
            options={
                "verbose_name": "Закон строения атомов и периодичности",
                "verbose_name_plural": "Законы строения атомов и периодичности",
            },
        ),
        migrations.AlterModelOptions(
            name="atomtest",
            options={
                "verbose_name": "Вопросы к разделу: законы строения атомов и периодичности",
                "verbose_name_plural": "Вопрос к разделу: законы строения атомов и периодичности",
            },
        ),
        migrations.AddField(
            model_name="atomlaw",
            name="presentation",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="presentations/",
                verbose_name="Файл презентации",
            ),
        ),
        migrations.AlterField(
            model_name="atomtest",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="atomtest",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос"),
        ),
    ]
