# Generated by Django 4.2.19 on 2026-01-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0015_alter_atomlaw_options_alter_atomtest_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="таблица",
                    ),
                ),
            ],
            options={
                "verbose_name": "Таблица по химии",
                "verbose_name_plural": "Таблицы по химии",
            },
        ),
        migrations.AlterModelOptions(
            name="atomtest",
            options={
                "verbose_name": "Вопросы к разделу: законы строения атомов и периодичности",
                "verbose_name_plural": "Вопросы к разделу: законы строения атомов и периодичности",
            },
        ),
        migrations.AddField(
            model_name="atomlaw",
            name="video",
            field=models.CharField(
                blank=True, max_length=10000, null=True, verbose_name="Видео"
            ),
        ),
        migrations.AddField(
            model_name="atomtest",
            name="img1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация1",
            ),
        ),
        migrations.AddField(
            model_name="atomtest",
            name="img2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация2",
            ),
        ),
        migrations.AddField(
            model_name="atomtest",
            name="img3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация3",
            ),
        ),
        migrations.AddField(
            model_name="atomtest",
            name="video",
            field=models.CharField(
                blank=True, max_length=10000, null=True, verbose_name="Видео"
            ),
        ),
        migrations.AddField(
            model_name="inorganiclaw",
            name="video",
            field=models.CharField(
                blank=True, max_length=10000, null=True, verbose_name="Видео"
            ),
        ),
        migrations.AddField(
            model_name="inorganicreaction",
            name="img1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация1",
            ),
        ),
        migrations.AddField(
            model_name="inorganicreaction",
            name="img2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация2",
            ),
        ),
        migrations.AddField(
            model_name="inorganicreaction",
            name="img3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация3",
            ),
        ),
        migrations.AddField(
            model_name="namescompaunds",
            name="img1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация1",
            ),
        ),
        migrations.AddField(
            model_name="namescompaunds",
            name="img2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация2",
            ),
        ),
        migrations.AddField(
            model_name="namescompaunds",
            name="img3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация3",
            ),
        ),
        migrations.AddField(
            model_name="namescompaunds",
            name="video",
            field=models.CharField(
                blank=True, max_length=10000, null=True, verbose_name="Видео"
            ),
        ),
    ]
