# Generated by Django 4.2.19 on 2026-01-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0016_table_alter_atomtest_options_atomlaw_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inorganiclaw",
            name="presentation",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="presentations/",
                verbose_name="Файл презентации",
            ),
        ),
    ]
