# Generated by Django 4.2.19 on 2026-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0017_inorganiclaw_presentation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(blank=True, null=True, verbose_name="Тип")),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Заголовок"),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="Ссылка"),
                ),
            ],
            options={
                "verbose_name": "Ссылка по химии",
                "verbose_name_plural": "Ссылки по химии",
            },
        ),
        migrations.AlterField(
            model_name="inorganicreaction",
            name="video",
            field=models.CharField(
                blank=True, max_length=10000, null=True, verbose_name="Видео"
            ),
        ),
    ]
