# Generated by Django 4.2.19 on 2026-02-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0020_organicnames"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganicNames",
        ),
    ]
