# Generated by Django 4.2.19 on 2026-02-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0021_delete_organicnames"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganicNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("molecule", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Органическое соединение",
                "verbose_name_plural": "Органические соединения",
            },
        ),
    ]
