# Generated by Django 4.2.19 on 2026-02-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Chem", "0022_organicnames"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organiclaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "metatitle",
                    models.CharField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="Метазаголовок страницы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Метаописание страницы"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Номер закона"
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Заголовок"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание закона"
                    ),
                ),
                (
                    "examples",
                    models.TextField(blank=True, null=True, verbose_name="Примеры"),
                ),
                (
                    "trening",
                    models.TextField(blank=True, null=True, verbose_name="Ссылки"),
                ),
                (
                    "img1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация1",
                    ),
                ),
                (
                    "img2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация2",
                    ),
                ),
                (
                    "img3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация3",
                    ),
                ),
                (
                    "video",
                    models.CharField(
                        blank=True, max_length=10000, null=True, verbose_name="Видео"
                    ),
                ),
                (
                    "presentation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="presentations/",
                        verbose_name="Файл презентации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Закон органической химии",
                "verbose_name_plural": "Законы органической химии",
            },
        ),
        migrations.CreateModel(
            name="OrganicReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "metatitle",
                    models.CharField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="Метазаголовок страницы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Метаописание страницы"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "reagent1",
                    models.CharField(blank=True, null=True, verbose_name="Реагент1"),
                ),
                (
                    "reagent2",
                    models.CharField(blank=True, null=True, verbose_name="Реагент2"),
                ),
                (
                    "reagent3",
                    models.CharField(blank=True, null=True, verbose_name="Реагент3"),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        default="нормальные условия",
                        null=True,
                        verbose_name="Условия реакции",
                    ),
                ),
                (
                    "product1",
                    models.CharField(blank=True, null=True, verbose_name="Продукт1"),
                ),
                (
                    "product2",
                    models.CharField(blank=True, null=True, verbose_name="Продукт1"),
                ),
                (
                    "product3",
                    models.CharField(blank=True, null=True, verbose_name="Продукт1"),
                ),
                (
                    "product4",
                    models.CharField(blank=True, null=True, verbose_name="Продукт1"),
                ),
                (
                    "extra",
                    models.CharField(
                        blank=True, null=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[("ОГЭ", "ОГЭ"), ("ЕГЭ", "ЕГЭ")],
                        default="ЕГЭ",
                        null=True,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "img1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация1",
                    ),
                ),
                (
                    "img2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация2",
                    ),
                ),
                (
                    "img3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация3",
                    ),
                ),
                (
                    "video",
                    models.CharField(
                        blank=True, max_length=10000, null=True, verbose_name="Видео"
                    ),
                ),
                (
                    "number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Chem.organiclaw",
                        verbose_name="Закон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реакция органической химии",
                "verbose_name_plural": "Реакции органической химии",
                "unique_together": {
                    ("reagent1", "reagent2", "reagent3", "condition", "number")
                },
            },
        ),
        migrations.RemoveField(
            model_name="organicnames",
            name="name",
        ),
        migrations.AddField(
            model_name="organicnames",
            name="appearance",
            field=models.TextField(blank=True, null=True, verbose_name="Внешний вид"),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="formula",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                unique=True,
                verbose_name="Формула",
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="img1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация1",
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="img2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация2",
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="img3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_images",
                verbose_name="Иллюстрация3",
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="name1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Название 1",
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="name2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Название 2",
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="name3",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Название 3",
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="name4",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Название 4",
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="video",
            field=models.CharField(
                blank=True, max_length=10000, null=True, verbose_name="Видео"
            ),
        ),
        migrations.AlterField(
            model_name="organicnames",
            name="molecule",
            field=models.TextField(
                blank=True, null=True, verbose_name="Структура молекулы"
            ),
        ),
        migrations.CreateModel(
            name="OrganicUserReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Chem.organicreaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organic_favorite_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "reaction")},
            },
        ),
    ]
