# Generated by Django 4.2.19 on 2026-02-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0023_organiclaw_organicreaction_remove_organicnames_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organiclaw",
            name="examples",
        ),
    ]
