# Generated by Django 4.2.19 on 2026-02-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0024_remove_organiclaw_examples"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organicnames",
            name="formula",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                unique=True,
                verbose_name="Молекулярная формула",
            ),
        ),
        migrations.AlterField(
            model_name="organicnames",
            name="molecule",
            field=models.TextField(
                blank=True, null=True, verbose_name="Структурная формула"
            ),
        ),
    ]
