# Generated by Django 4.2.19 on 2026-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0026_organicnames_organic_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicnames",
            name="molecule_short",
            field=models.TextField(
                blank=True, null=True, verbose_name="сокращенная структурная формула"
            ),
        ),
        migrations.AlterField(
            model_name="organicnames",
            name="organic_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alkanes", "Алканы"),
                    ("alkenes", "Алкены"),
                    ("alkynes", "Алкины"),
                    ("alkadienes", "Алкадиены"),
                    ("cycloalkanes", "Циклоалканы"),
                    ("arenes", "Арены"),
                    ("alcohols", "Спирты"),
                    ("phenols", "Фенолы"),
                    ("ethers", "Простые эфиры"),
                    ("aldehydes", "Альдегиды"),
                    ("ketones", "Кетоны"),
                    ("carboxylic_acids", "Карбоновые кислоты"),
                    ("esters", "Сложные эфиры"),
                    ("fats", "Жиры"),
                    ("carbohydrates", "Углеводы"),
                    ("amines", "Амины"),
                    ("nitro_compounds", "Нитросоединения"),
                    ("amino_acids", "Аминокислоты"),
                    ("proteins", "Белки"),
                    ("nucleic_acids", "Нуклеиновые кислоты"),
                    ("halogen_derivatives", "Галогенопроизводные"),
                    ("thiols", "Тиолы"),
                    ("heterocycles", "Гетероциклы"),
                    ("organometallic_compounds", "Элементоорганические соединения"),
                    ("inorganic_compounds", "Неорганические соединения"),
                ],
                default="ЕГЭ",
                null=True,
                verbose_name="Класс",
            ),
        ),
    ]
