# Generated by Django 4.2.19 on 2026-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0027_organicnames_molecule_short_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organicnames",
            name="formula",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Молекулярная формула",
            ),
        ),
        migrations.AlterField(
            model_name="organicnames",
            name="name2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название 2"
            ),
        ),
        migrations.AlterField(
            model_name="organicnames",
            name="name3",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название 3"
            ),
        ),
        migrations.AlterField(
            model_name="organicnames",
            name="name4",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название 4"
            ),
        ),
    ]
