# Generated by Django 4.2.19 on 2026-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0029_alter_atomlaw_options_alter_atomtest_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Videor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "metatitle",
                    models.CharField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="Метазаголовок страницы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Метаописание страницы"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Заголовок"),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "video",
                    models.CharField(
                        blank=True, max_length=10000, null=True, verbose_name="Видео"
                    ),
                ),
                (
                    "presentation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="presentations/",
                        verbose_name="Файл презентации",
                    ),
                ),
                (
                    "img1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация1",
                    ),
                ),
                (
                    "img2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация2",
                    ),
                ),
                (
                    "img3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видеореакция",
                "verbose_name_plural": "Видеореакции",
            },
        ),
        migrations.AlterField(
            model_name="organicnames",
            name="organic_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alkanes", "Алканы"),
                    ("alkenes", "Алкены"),
                    ("alkynes", "Алкины"),
                    ("alkadienes", "Алкадиены"),
                    ("cycloalkanes", "Циклоалканы"),
                    ("arenes", "Арены"),
                    ("alcohols", "Спирты"),
                    ("phenols", "Фенолы"),
                    ("ethers", "Простые эфиры"),
                    ("aldehydes", "Альдегиды"),
                    ("ketones", "Кетоны"),
                    ("carboxylic_acids", "Карбоновые кислоты"),
                    ("esters", "Сложные эфиры"),
                    ("fats", "Жиры"),
                    ("carbohydrates", "Углеводы"),
                    ("amines", "Амины"),
                    ("nitro_compounds", "Нитросоединения"),
                    ("amino_acids", "Аминокислоты"),
                    ("дипептиды", "Дипептиды"),
                    ("proteins", "Белки"),
                    ("nucleic_acids", "Нуклеиновые кислоты"),
                    ("halogen_derivatives", "Галогенопроизводные"),
                    ("thiols", "Тиолы"),
                    ("heterocycles", "Гетероциклы"),
                    ("carboxylic_acids_salts", "Соли карбоновых кислот"),
                    ("organometallic_compounds", "Элементоорганические соединения"),
                    ("Полимеры", "Полимеры"),
                    ("Ацетилениды", "Ацетилениды"),
                    ("Бифункциональное соединение", "Бифункциональное соединение"),
                    ("Циангидрины", "Циангидрины"),
                    ("Нитрилы", "Нитрилы"),
                    ("Алкоголяты металлов", "Алкоголяты металлов"),
                    ("Соли аминов", "Соли аминов"),
                    ("Галогениды аминов", "Галогениды аминов"),
                    ("Ангидриды", "Ангидриды"),
                    ("Хлорангидриды", "Хлорангидриды"),
                    ("Соли сульфокислоты", "Соли сульфокислоты"),
                    ("Нитропроизводные фенола", "Нитропроизводные фенола"),
                    ("Нитрозамины", "Нитрозамины"),
                    ("inorganic_compounds", "Неорганические соединения"),
                ],
                default="ЕГЭ",
                null=True,
                verbose_name="Класс",
            ),
        ),
    ]
