# Generated by Django 4.2.19 on 2026-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0031_atomlaw_img4_atomlaw_img5_atomlaw_img6_atomtest_img4_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pictures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images",
                        verbose_name="Иллюстрация1",
                    ),
                ),
            ],
            options={
                "verbose_name": "картинки",
                "verbose_name_plural": "картинки",
            },
        ),
    ]
