# Generated by Django 4.2.19 on 2026-07-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0032_pictures"),
    ]

    operations = [
        migrations.AddField(
            model_name="namescompaunds",
            name="is_interesting",
            field=models.BooleanField(
                default=False, verbose_name="вещество о котором надо узнать больше"
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="test_formula_to_class",
            field=models.BooleanField(
                default=True, verbose_name="тест формула-класс веществ да"
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="test_name_to_structure",
            field=models.BooleanField(
                default=True, verbose_name="тест название-структура да"
            ),
        ),
        migrations.AddField(
            model_name="organicnames",
            name="test_structure_to_name",
            field=models.BooleanField(
                default=True, verbose_name="тест структура-название да"
            ),
        ),
    ]
