# Generated by Django 4.2.19 on 2026-07-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chem", "0033_namescompaunds_is_interesting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicnames",
            name="is_interesting",
            field=models.BooleanField(
                default=False, verbose_name="вещество о котором надо узнать больше"
            ),
        ),
    ]
